name = "website"
main = "worker.js"
compatibility_date = "2024-01-01"

[env.production]
name = "website-production"

# Static assets configuration
[site]
bucket = "./"
entry-point = "worker.js"

# Build configuration
[build]
command = ""
cwd = "./"
watch_dir = "./"

# Custom domain (update with your domain)
# routes = [
#   { pattern = "yoursite.com/*", zone_name = "yoursite.com" }
# ]