name = "website"
main = "worker.js"
compatibility_date = "2024-01-01"

[site]
bucket = "./"
entry-point = "worker.js"

# Custom domain (update with your domain)
# routes = [
#   { pattern = "yoursite.com/*", zone_name = "yoursite.com" }
# ]